import type { SpreadsheetStore } from '../store/store.js';
import { getRecentFunctions } from './function-history.js';
import { interactionControllerFor } from './interaction-controller.js';
import type {
  InteractionOperation,
  InteractionOrigin,
  OperationEffect,
  OperationIntent,
  PermissionDecision,
} from './interaction-policy.js';
import { FUNCTION_SIGNATURES } from './refs.js';

/** Stable built-in command classification. Keep this explicit: an unknown
 * command must not become executable merely because a host allowed a broad
 * operation category. */
export const BUILT_IN_COMMAND_OPERATION: Readonly<Record<string, InteractionOperation>> = {
  paste: 'paste',
  pasteSpecial: 'paste',
  pasteAll: 'paste',
  pasteValues: 'paste',
  pasteValuesNumFmt: 'paste',
  pasteTranspose: 'paste',
  pasteFormatsOnly: 'format',
  pasteFormulas: 'formulaEdit',
  pasteFormulasNumFmt: 'formulaEdit',
  cut: 'moveCells',
  clear: 'clear',
  insertCells: 'insertRows',
  insertCopiedCells: 'moveCells',
  deleteCells: 'deleteRows',
  rowInsertAbove: 'insertRows',
  rowInsertBelow: 'insertRows',
  rowDelete: 'deleteRows',
  colInsertLeft: 'insertColumns',
  colInsertRight: 'insertColumns',
  colDelete: 'deleteColumns',
  rowHeight: 'resizeRows',
  colWidth: 'resizeColumns',
  bold: 'format',
  italic: 'format',
  underline: 'format',
  strike: 'format',
  alignLeft: 'format',
  alignCenter: 'format',
  alignRight: 'format',
  // Home ribbon format mutators and the inline font/number controls.
  currency: 'format',
  percent: 'format',
  comma: 'format',
  alignL: 'format',
  alignC: 'format',
  alignR: 'format',
  top: 'format',
  middle: 'format',
  bottomAlign: 'format',
  decUp: 'format',
  decDown: 'format',
  wrap: 'format',
  general: 'format',
  textOrientation: 'format',
  indentDecrease: 'format',
  indentIncrease: 'format',
  fontGrow: 'format',
  fontShrink: 'format',
  fontFamily: 'format',
  fontSize: 'format',
  fontColor: 'format',
  fillColor: 'format',
  numberFormat: 'format',
  borders: 'format',
  formatCells: 'format',
  defineName: 'namedRange',
  filterClear: 'filter',
  filterReapply: 'filter',
  filterByValue: 'filter',
  sortAsc: 'sort',
  sortDesc: 'sort',
  insertComment: 'comment',
  deleteComment: 'comment',
  insertHyperlink: 'hyperlink',
  editPhonetic: 'format',
  protect: 'protection',
  protectReview: 'protection',
  pageSetup: 'pageSetup',
  print: 'print',
  export: 'export',
  printArea: 'pageSetup',
  pageBreaks: 'pageSetup',
  dataValidation: 'validation',
  namedRanges: 'namedRange',
  formatTableInsert: 'table',
  formatTableHome: 'table',
  pivotTableInsert: 'table',
  chartInsert: 'object',
  pictureInsert: 'object',
  shapesInsert: 'object',
  screenshotInsert: 'object',
  workbookObjectsView: 'object',
  sheetInsert: 'sheet',
  sheetDelete: 'sheet',
  sheetRename: 'sheet',
  undo: 'valueEdit',
  redo: 'valueEdit',
  scaleWidth: 'pageSetup',
  scaleHeight: 'pageSetup',
  sheetViewSelect: 'format',

  // Excel 365 Mac ribbon actions. Keep these aliases explicit so a restricted
  // embed cannot gain a new mutation merely by adopting the Mac profile.
  'mac.insert.pivotTable': 'table',
  'mac.insert.recommendedPivotTable': 'table',
  'mac.insert.table': 'table',
  'mac.insert.forms': 'object',
  'mac.insert.photo': 'object',
  'mac.insert.shapeRectangle': 'object',
  'mac.insert.shapeArrow': 'object',
  'mac.insert.shapeLine': 'object',
  'mac.insert.shapeRoundedRectangle': 'object',
  'mac.insert.shapeOval': 'object',
  'mac.insert.shapeTriangle': 'object',
  'mac.insert.shapeDiamond': 'object',
  'mac.insert.shapeCallout': 'object',
  'mac.insert.icons': 'object',
  'mac.insert.threeDModel': 'object',
  'mac.insert.smartArt': 'object',
  'mac.insert.screenshot': 'object',
  'mac.insert.checkBox': 'object',
  'mac.insert.chartColumn': 'object',
  'mac.insert.chartBar': 'object',
  'mac.insert.chartLine': 'object',
  'mac.insert.chartArea': 'object',
  'mac.insert.chartPie': 'object',
  'mac.insert.chartScatter': 'object',
  'mac.insert.chartHierarchy': 'object',
  'mac.insert.chartStatistical': 'object',
  'mac.insert.chartWaterfall': 'object',
  'mac.insert.chartCombo': 'object',
  'mac.insert.chartMap': 'object',
  'mac.insert.pivotChart': 'object',
  'mac.insert.sparkline': 'object',
  'mac.insert.slicer': 'table',
  'mac.insert.link': 'hyperlink',
  'mac.insert.newComment': 'comment',
  'mac.insert.textBox': 'object',
  'mac.insert.headerFooter': 'pageSetup',
  'mac.insert.wordArt': 'object',
  'mac.insert.object': 'object',
  'mac.insert.equation': 'formulaEdit',
  'mac.insert.pictureFromData': 'object',
  'mac.home.addins': 'object',
  'mac.draw.toggle': 'object',
  'mac.draw.lasso': 'object',
  'mac.draw.penBlack': 'object',
  'mac.draw.penRed': 'object',
  'mac.draw.pencil': 'object',
  'mac.draw.highlighter': 'object',
  'mac.draw.trackpad': 'object',
  'mac.page.background': 'pageSetup',
  'mac.page.printTitles': 'pageSetup',
  'mac.page.pageSetup': 'pageSetup',
  'mac.page.scaleWidth': 'pageSetup',
  'mac.page.scaleHeight': 'pageSetup',
  'mac.page.showGridlines': 'pageSetup',
  'mac.page.printGridlines': 'pageSetup',
  'mac.page.showHeadings': 'pageSetup',
  'mac.page.printHeadings': 'pageSetup',
  'mac.formulas.insertFunction': 'formulaEdit',
  'mac.autosum.SUM': 'formulaEdit',
  'mac.autosum.AVERAGE': 'formulaEdit',
  'mac.autosum.COUNT': 'formulaEdit',
  'mac.autosum.MAX': 'formulaEdit',
  'mac.autosum.MIN': 'formulaEdit',
  'mac.formulas.namesManager': 'namedRange',
  'mac.formulas.defineName': 'namedRange',
  'mac.formulas.useInFormula': 'formulaEdit',
  'mac.formulas.createFromSelection': 'namedRange',
  'mac.formulas.removeArrows.all': 'formulaEdit',
  'mac.formulas.removeArrows.precedents': 'formulaEdit',
  'mac.formulas.removeArrows.dependents': 'formulaEdit',
  'mac.formulas.errorCheck.trace': 'formulaEdit',
  'mac.formulas.errorCheck.ignore': 'formulaEdit',
  'mac.formulas.precedents': 'formulaEdit',
  'mac.formulas.dependents': 'formulaEdit',
  'mac.formulas.recalc': 'formulaEdit',
  'mac.formulas.sheetRecalc': 'formulaEdit',
  // Keep every function leaf in lockstep with the engine catalog. This is
  // deliberately generated from known signatures; an arbitrary
  // `mac.function.*` id remains denied below.
  ...Object.fromEntries(
    Object.keys(FUNCTION_SIGNATURES).map((name) => [
      `mac.function.${name}`,
      'formulaEdit' as InteractionOperation,
    ]),
  ),
  'mac.page.margins.normal': 'pageSetup',
  'mac.page.margins.wide': 'pageSetup',
  'mac.page.margins.narrow': 'pageSetup',
  'mac.page.margins.custom': 'pageSetup',
  'mac.page.orientation.portrait': 'pageSetup',
  'mac.page.orientation.landscape': 'pageSetup',
  'mac.page.size.a4': 'pageSetup',
  'mac.page.size.a3': 'pageSetup',
  'mac.page.size.letter': 'pageSetup',
  'mac.page.size.legal': 'pageSetup',
  'mac.page.printArea.set': 'pageSetup',
  'mac.page.printArea.add': 'pageSetup',
  'mac.page.printArea.clear': 'pageSetup',
  'mac.page.break.insert': 'pageSetup',
  'mac.page.break.remove': 'pageSetup',
  'mac.page.break.reset': 'pageSetup',
  'mac.formulas.createNames.topRow': 'namedRange',
  'mac.formulas.createNames.bottomRow': 'namedRange',
  'mac.formulas.createNames.leftColumn': 'namedRange',
  'mac.formulas.createNames.rightColumn': 'namedRange',
  'mac.formulas.calc.auto': 'formulaEdit',
  'mac.formulas.calc.autoNoTable': 'formulaEdit',
  'mac.formulas.calc.manual': 'formulaEdit',
  'mac.formulas.calc.iterative': 'formulaEdit',
  'mac.view.freeze.off': 'format',
  'mac.view.freeze.firstRow': 'format',
  'mac.view.freeze.firstColumn': 'format',
  'mac.data.refreshAll': 'valueEdit',
  'mac.data.sortAsc': 'sort',
  'mac.data.sortDesc': 'sort',
  'mac.data.sortCustom': 'sort',
  'mac.data.filter': 'filter',
  'mac.data.clear': 'filter',
  'mac.data.reapply': 'filter',
  'mac.data.advancedFilter': 'filter',
  'mac.data.textToColumns': 'valueEdit',
  'mac.data.flashFill': 'fill',
  'mac.data.removeDuplicates': 'valueEdit',
  'mac.data.validation.settings': 'validation',
  'mac.data.validation.circleInvalid': 'validation',
  'mac.data.validation.clearCircles': 'validation',
  'mac.data.validation.clearRules': 'validation',
  'mac.data.consolidate': 'valueEdit',
  'mac.data.whatIf': 'valueEdit',
  'mac.data.goalSeek': 'valueEdit',
  'mac.data.subtotal': 'valueEdit',
  'mac.data.group': 'format',
  'mac.data.ungroup': 'format',
  'mac.data.showDetail': 'format',
  'mac.data.hideDetail': 'format',
  'mac.data.analysis': 'object',
  'mac.review.newComment': 'comment',
  'mac.review.newNote': 'comment',
  'mac.review.previousNote': 'comment',
  'mac.review.nextNote': 'comment',
  'mac.review.protectSheet': 'protection',
  'mac.review.protectWorkbook': 'protection',
  'mac.view.freeze': 'format',
  'mac.view.split': 'format',
  'mac.view.sheetViewSave': 'format',
  'mac.view.sheetViewDelete': 'format',
  'mac.automate.showScripts': 'object',
  'mac.automate.allRowsColumns': 'format',
  'mac.automate.freezeSelection': 'format',
  'mac.automate.makeSubtable': 'table',
  'mac.automate.removeHyperlinks': 'hyperlink',
  'mac.automate.countEmptyRows': 'valueEdit',
  'mac.automate.tableToJson': 'export',
  'mac.automate.newPivotTable': 'table',
};

/** Ids that never mutate and so bypass the operation map; they are not listed there. */
const SAFE_NAVIGATION_COMMANDS: ReadonlySet<string> = new Set([
  'copy',
  'selectAll',
  'openHyperlink',
  'toggleWatch',
  'findHome',
  'gotoSpecial',
  'gotoSpecialHome',
  'viewNormal',
  'viewPageLayout',
  'viewPageBreakPreview',
  'zoom75',
  'zoom100',
  'zoom125',
  'zoomDialog',
  'mac.view.zoom100',
  'showFormulas',
  'r1c1',
  'mac.insert.recommendedChart',
  'mac.insert.shapes',
  'mac.draw.eraser',
  'mac.draw.add',
  'mac.page.color',
  'mac.page.font',
  'mac.page.margins',
  'mac.page.orientation',
  'mac.page.size',
  'mac.page.printArea',
  'mac.formulas.autoSum',
  'mac.formulas.recent',
  'mac.formulas.financial',
  'mac.formulas.logical',
  'mac.formulas.text',
  'mac.formulas.dateTime',
  'mac.formulas.lookup',
  'mac.formulas.math',
  'mac.formulas.more',
  'mac.formulas.removeArrows',
  'mac.formulas.errorCheck',
  'mac.formulas.category.recent',
  'mac.formulas.category.all',
  'mac.formulas.showFormulas',
  'mac.formulas.watch',
  'mac.formulas.calcOptions',
  'mac.page.pageBreaks',
  'linksData',
  'mac.data.workbookLinks',
  'mac.data.dataTypes',
  'mac.data.sortFilter',
  'mac.data.validation',
  'mac.review.spelling',
  'mac.review.stats',
  'mac.review.accessibility',
  'mac.review.translate',
  'mac.review.showComments',
  'mac.review.showNotes',
  'mac.view.standard',
  'mac.view.pageLayout',
  'mac.view.pageBreakPreview',
  'mac.view.customViews',
  'mac.view.show',
  'mac.view.zoom',
  'mac.view.zoomSelection',
  'mac.view.newWindow',
  'mac.view.arrange',
  'mac.view.switchWindow',
  'mac.automate.gallery',
]);

/** Commands whose useful effect is moving the active selection. These follow
 * the host's separate selection permission instead of the mutation policy. */
const SELECTING_NAVIGATION_COMMANDS: ReadonlySet<string> = new Set([
  'selectAll',
  'mac.formulas.errorCheck.run',
]);

const SELECTION_FORMAT_COMMANDS: ReadonlySet<string> = new Set([
  'bold',
  'italic',
  'underline',
  'strike',
  'currency',
  'percent',
  'comma',
  'alignLeft',
  'alignCenter',
  'alignRight',
  'alignL',
  'alignC',
  'alignR',
  'top',
  'middle',
  'bottomAlign',
  'decUp',
  'decDown',
  'wrap',
  'general',
  'textOrientation',
  'indentDecrease',
  'indentIncrease',
  'fontGrow',
  'fontShrink',
  'fontFamily',
  'fontSize',
  'fontColor',
  'fillColor',
  'numberFormat',
]);

const unsupported = (id: string): PermissionDecision => ({
  allowed: false,
  code: 'unsupported',
  reason: `built-in command ${id} is not classified for restricted execution`,
});

export function canExecuteBuiltIn(
  store: SpreadsheetStore,
  id: string,
  origin: InteractionOrigin,
): PermissionDecision {
  const controller = interactionControllerFor(store);
  if (!controller?.restricted) return { allowed: true };
  if (id === 'copy') return controller.canCopy();
  if (SELECTING_NAVIGATION_COMMANDS.has(id)) return controller.canSelect();
  if (SAFE_NAVIGATION_COMMANDS.has(id)) return { allowed: true };
  const dynamicFunctionName = id.startsWith('mac.function.')
    ? id.slice('mac.function.'.length)
    : null;
  const dynamicFunctionRecorded =
    dynamicFunctionName !== null &&
    getRecentFunctions(store, new Set([dynamicFunctionName])).includes(dynamicFunctionName);
  const operation =
    BUILT_IN_COMMAND_OPERATION[id] ?? (dynamicFunctionRecorded ? 'formulaEdit' : undefined);
  if (!operation) return unsupported(id);
  if (operation === 'format' && !SELECTION_FORMAT_COMMANDS.has(id)) return unsupported(id);
  const state = store.getState();
  const selectionFormat =
    operation === 'format' && SELECTION_FORMAT_COMMANDS.has(id)
      ? [state.selection.range, ...(state.selection.extraRanges ?? [])].map(
          (range): OperationEffect => ({ kind: 'range', range }),
        )
      : null;
  const intent: OperationIntent = {
    operation,
    origin,
    commandId: id,
    effects:
      operation === 'print' || operation === 'export'
        ? [{ kind: 'workbook' }]
        : (selectionFormat ?? [{ kind: 'range', range: state.selection.range }]),
  };
  return controller.canExecute(intent);
}
