import type { ToolbarLang } from '../../ribbon-model.js';
import { MAC_AUTOMATION_GALLERY, MAC_AUTOMATION_GALLERY_TITLE } from './automation-gallery.js';

export type Label = { ja: string; en: string };

export const text = (lang: ToolbarLang, label: Label): string => label[lang];

export const OFFICE_REQUIRED: Label = {
  ja: 'クラウドサービスへの接続が必要です。',
  en: 'Requires a cloud service connection.',
};
export const NOT_IMPLEMENTED: Label = {
  ja: 'この機能は未実装です。',
  en: 'This feature is not implemented yet.',
};
export const EMBEDDED_UNSUPPORTED: Label = {
  ja: 'この埋め込み環境では未対応です。',
  en: 'This feature is not available in the embedded workbook.',
};
export const WORKBOOK_THEME_UNSUPPORTED: Label = {
  ja: 'ブックのテーマはこの埋め込み環境では変更できません。',
  en: 'Workbook themes cannot be changed in the embedded workbook.',
};
export const THREADED_COMMENTS_UNSUPPORTED: Label = {
  ja: 'スレッド形式のコメントは未対応です。セルのメモを使用してください。',
  en: 'Threaded comments are unavailable; use cell notes instead.',
};

export const labels: Record<string, Label> = {
  home: { ja: 'ホーム', en: 'Home' },
  addins: { ja: 'アドイン', en: 'Add-ins' },
  pivotTable: { ja: 'ピボットテーブル', en: 'PivotTable' },
  recommendedPivotTable: { ja: 'おすすめピボットテーブル', en: 'Recommended PivotTables' },
  table: { ja: 'テーブル', en: 'Table' },
  forms: { ja: 'フォーム', en: 'Forms' },
  pictureFromFile: { ja: '画像から', en: 'Picture from File' },
  pictureFromOnline: { ja: 'オンライン画像', en: 'Online Pictures' },
  photo: { ja: '写真', en: 'Photos' },
  shapes: { ja: '図形', en: 'Shapes' },
  icons: { ja: 'アイコン', en: 'Icons' },
  threeDModel: { ja: '3D モデル', en: '3D Models' },
  smartArt: { ja: 'SmartArt', en: 'SmartArt' },
  screenshot: { ja: 'スクリーンショット', en: 'Screenshot' },
  checkBox: { ja: 'チェック ボックス', en: 'Checkbox' },
  recommendedChart: { ja: 'おすすめグラフ', en: 'Recommended Charts' },
  chartColumn: { ja: '縦棒', en: 'Column' },
  chartBar: { ja: '横棒', en: 'Bar' },
  chartLine: { ja: '折れ線', en: 'Line' },
  chartArea: { ja: '面', en: 'Area' },
  chartPie: { ja: '円', en: 'Pie' },
  chartHierarchy: { ja: '階層', en: 'Hierarchy' },
  chartStatistical: { ja: '統計', en: 'Statistical' },
  chartScatter: { ja: '散布図', en: 'Scatter' },
  chartWaterfall: { ja: 'ウォーターフォール', en: 'Waterfall' },
  chartCombo: { ja: '組み合わせ', en: 'Combo' },
  chartMap: { ja: 'マップ', en: 'Map' },
  pivotChart: { ja: 'ピボットグラフ', en: 'PivotChart' },
  sparkline: { ja: 'スパークライン', en: 'Sparklines' },
  slicer: { ja: 'スライサー', en: 'Slicer' },
  timeline: { ja: 'タイムライン', en: 'Timeline' },
  insert: { ja: '挿入', en: 'Insert' },
  formulas: { ja: '数式', en: 'Formulas' },
  data: { ja: 'データ', en: 'Data' },
  review: { ja: '校閲', en: 'Review' },
  view: { ja: '表示', en: 'View' },
  automate: { ja: '自動化', en: 'Automate' },
  sortFilter: { ja: '並べ替えとフィルター', en: 'Sort & Filter' },
  sheetViews: { ja: 'シート ビュー', en: 'Sheet Views' },
  shapeLine: { ja: '直線', en: 'Line' },
  shapeRectangle: { ja: '四角形', en: 'Rectangle' },
  shapeRoundedRectangle: { ja: '角丸四角形', en: 'Rounded Rectangle' },
  shapeOval: { ja: '楕円', en: 'Oval' },
  shapeTriangle: { ja: '三角形', en: 'Triangle' },
  shapeDiamond: { ja: 'ひし形', en: 'Diamond' },
  shapeArrow: { ja: '矢印', en: 'Arrow' },
  shapeCallout: { ja: '吹き出し', en: 'Callout' },
  gridlines: { ja: '枠線', en: 'Gridlines' },
  headings: { ja: '見出し', en: 'Headings' },
  formulaBar: { ja: '数式バー', en: 'Formula Bar' },
  zeros: { ja: 'ゼロ値', en: 'Zero Values' },
  link: { ja: 'リンク', en: 'Link' },
  newComment: { ja: '新しいコメント', en: 'New Comment' },
  textBox: { ja: 'テキスト ボックス', en: 'Text Box' },
  headerFooter: { ja: 'ヘッダーとフッター', en: 'Header & Footer' },
  wordArt: { ja: 'ワードアート', en: 'WordArt' },
  object: { ja: 'オブジェクト', en: 'Object' },
  equation: { ja: '数式', en: 'Equation' },
  symbol: { ja: '記号と特殊文字', en: 'Symbols' },
  draw: { ja: '描画', en: 'Draw' },
  toggle: { ja: '描画', en: 'Draw' },
  eraser: { ja: '消しゴム', en: 'Eraser' },
  lasso: { ja: 'なげわ選択', en: 'Lasso Select' },
  penBlack: { ja: 'ペン（黒）', en: 'Black Pen' },
  penRed: { ja: 'ペン（赤）', en: 'Red Pen' },
  pencil: { ja: '鉛筆書き（灰）', en: 'Pencil' },
  highlighter: { ja: '蛍光ペン（黄）', en: 'Highlighter' },
  add: { ja: '追加', en: 'Add Pen' },
  trackpad: { ja: 'トラックパッドで描画', en: 'Draw with Trackpad' },
  theme: { ja: 'テーマ', en: 'Themes' },
  color: { ja: '色', en: 'Colors' },
  font: { ja: 'フォント', en: 'Fonts' },
  margins: { ja: '余白', en: 'Margins' },
  orientation: { ja: '印刷の向き', en: 'Orientation' },
  size: { ja: 'サイズ', en: 'Size' },
  printArea: { ja: '印刷範囲', en: 'Print Area' },
  pageBreaks: { ja: '改ページ', en: 'Breaks' },
  background: { ja: '背景', en: 'Background' },
  printTitles: { ja: '印刷タイトル', en: 'Print Titles' },
  pageSetup: { ja: 'ページ設定', en: 'Page Setup' },
  width: { ja: '幅', en: 'Width' },
  height: { ja: '高さ', en: 'Height' },
  scaleWidth: { ja: '幅', en: 'Width' },
  scaleHeight: { ja: '高さ', en: 'Height' },
  showGridlines: { ja: '表示（枠線）', en: 'View Gridlines' },
  printGridlines: { ja: '印刷（枠線）', en: 'Print Gridlines' },
  showHeadings: { ja: '表示（見出し）', en: 'View Headings' },
  printHeadings: { ja: '印刷（見出し）', en: 'Print Headings' },
  insertFunction: { ja: '関数の挿入', en: 'Insert Function' },
  autoSum: { ja: 'オートSUM', en: 'AutoSum' },
  recent: { ja: '最近使ったもの', en: 'Recently Used' },
  financial: { ja: '財務', en: 'Financial' },
  logical: { ja: '論理', en: 'Logical' },
  text: { ja: '文字列操作', en: 'Text' },
  dateTime: { ja: '日付/時刻', en: 'Date & Time' },
  lookup: { ja: '検索/行列', en: 'Lookup & Reference' },
  math: { ja: '数学/三角', en: 'Math & Trig' },
  more: { ja: 'その他の関数', en: 'More Functions' },
  statistical: { ja: '統計', en: 'Statistical' },
  dynamicArray: { ja: '動的配列', en: 'Dynamic Array' },
  allFunctions: { ja: 'すべての関数', en: 'All Functions' },
  python: { ja: 'Python の挿入', en: 'Insert Python' },
  reset: { ja: 'リセット', en: 'Reset' },
  editor: { ja: 'エディター', en: 'Editor' },
  initialize: { ja: '初期化', en: 'Initialize' },
  namesManager: { ja: 'ネームマネージャー', en: 'Name Manager' },
  defineName: { ja: '名前の定義', en: 'Define Name' },
  useInFormula: { ja: '数式で使用', en: 'Use in Formula' },
  createFromSelection: { ja: '選択範囲から作成', en: 'Create from Selection' },
  precedents: { ja: '参照元のトレース', en: 'Trace Precedents' },
  dependents: { ja: '参照先のトレース', en: 'Trace Dependents' },
  removeArrows: { ja: 'トレース矢印の削除', en: 'Remove Arrows' },
  showFormulas: { ja: '数式の表示', en: 'Show Formulas' },
  errorCheck: { ja: 'エラーチェック', en: 'Error Checking' },
  watch: { ja: 'ウォッチウィンドウ', en: 'Watch Window' },
  calcOptions: { ja: '計算方法の設定', en: 'Calculation Options' },
  recalc: { ja: '再計算実行', en: 'Calculate Now' },
  sheetRecalc: { ja: 'シート再計算', en: 'Calculate Sheet' },
  powerQuery: { ja: 'データファイル指定', en: 'Get Data' },
  pictureFromData: { ja: '画像から', en: 'From Picture' },
  refreshAll: { ja: 'すべて更新', en: 'Refresh All' },
  queriesConnections: { ja: 'クエリと接続', en: 'Queries & Connections' },
  properties: { ja: 'プロパティ', en: 'Properties' },
  workbookLinks: { ja: 'ブックのリンク', en: 'Workbook Links' },
  dataTypes: { ja: 'データの種類', en: 'Data Types' },
  sortAsc: { ja: '昇順', en: 'Sort Ascending' },
  sortDesc: { ja: '降順', en: 'Sort Descending' },
  sortCustom: { ja: '並べ替え', en: 'Custom Sort' },
  filter: { ja: 'フィルター', en: 'Filter' },
  clear: { ja: 'クリア', en: 'Clear' },
  reapply: { ja: '再適用', en: 'Reapply' },
  advancedFilter: { ja: '詳細設定', en: 'Advanced' },
  textToColumns: { ja: '区切り位置', en: 'Text to Columns' },
  flashFill: { ja: 'フラッシュフィル', en: 'Flash Fill' },
  removeDuplicates: { ja: '重複削除', en: 'Remove Duplicates' },
  validation: { ja: '入力規則', en: 'Data Validation' },
  consolidate: { ja: '統合', en: 'Consolidate' },
  whatIf: { ja: 'What-If 分析', en: 'What-If Analysis' },
  group: { ja: 'グループ化', en: 'Group' },
  ungroup: { ja: 'グループ解除', en: 'Ungroup' },
  subtotal: { ja: '小計', en: 'Subtotal' },
  showDetail: { ja: '詳細データ表示', en: 'Show Detail' },
  hideDetail: { ja: '詳細を表示しない', en: 'Hide Detail' },
  analysis: { ja: '分析ツール', en: 'Analysis ToolPak' },
  spelling: { ja: 'スペルチェック', en: 'Spelling' },
  thesaurus: { ja: '類義語辞典', en: 'Thesaurus' },
  stats: { ja: 'ブック統計', en: 'Workbook Statistics' },
  accessibility: { ja: 'アクセシビリティチェック', en: 'Check Accessibility' },
  translate: { ja: '翻訳', en: 'Translate' },
  showChanges: { ja: '変更内容を表示', en: 'Show Changes' },
  deleteComment: { ja: '削除', en: 'Delete Comment' },
  previousComment: { ja: '前', en: 'Previous Comment' },
  nextComment: { ja: '次', en: 'Next Comment' },
  showComments: { ja: 'コメントの表示', en: 'Show Comments' },
  notes: { ja: 'メモ', en: 'Notes' },
  protectSheet: { ja: 'シート保護', en: 'Protect Sheet' },
  protectWorkbook: { ja: 'ブック保護', en: 'Protect Workbook' },
  alwaysReadOnly: { ja: '常に読み取り専用で開く', en: 'Always Open Read-Only' },
  hideInk: { ja: 'インクを非表示にする', en: 'Hide Ink' },
  sheetView: { ja: 'シートビュー', en: 'Sheet View' },
  sheetViewSelect: { ja: '現在のビュー', en: 'Current View' },
  sheetViewSave: { ja: 'ビューを保存', en: 'Save View' },
  sheetViewDelete: { ja: 'ビューを削除', en: 'Delete View' },
  standard: { ja: '標準', en: 'Normal' },
  pageBreakPreview: { ja: '改ページプレビュー', en: 'Page Break Preview' },
  pageLayout: { ja: 'ページレイアウト', en: 'Page Layout' },
  customViews: { ja: 'ユーザー設定のビュー', en: 'Custom Views' },
  show: { ja: '表示', en: 'Show' },
  zoom: { ja: 'ズーム', en: 'Zoom' },
  zoomSelection: { ja: '選択範囲に合わせて拡大/縮小', en: 'Zoom to Selection' },
  newWindow: { ja: '新しいウィンドウ', en: 'New Window' },
  arrange: { ja: '整列', en: 'Arrange All' },
  freeze: { ja: 'ウィンドウ枠の固定', en: 'Freeze Panes' },
  split: { ja: '分割', en: 'Split' },
  hide: { ja: '非表示', en: 'Hide' },
  unhide: { ja: '再表示', en: 'Unhide' },
  sideBySide: { ja: '並べて比較', en: 'View Side by Side' },
  syncScroll: { ja: '同時にスクロール', en: 'Synchronous Scrolling' },
  resetWindow: { ja: 'ウィンドウ位置のリセット', en: 'Reset Window Position' },
  switchWindow: { ja: 'ウィンドウの切り替え', en: 'Switch Windows' },
  macros: { ja: 'マクロ', en: 'Macros' },
  newScript: { ja: '新しいスクリプト', en: 'New Script' },
  showScripts: { ja: 'スクリプトの表示', en: 'View Scripts' },
  gallery: MAC_AUTOMATION_GALLERY_TITLE,
};

export const t = (key: string): Label => labels[key] ?? { ja: key, en: key };

export const GROUP_LABELS: Readonly<Record<string, Label>> = {
  Tables: { ja: 'テーブル', en: 'Tables' },
  Forms: { ja: 'フォーム', en: 'Forms' },
  Pictures: { ja: '画像', en: 'Pictures' },
  Illustrations: { ja: 'イラスト', en: 'Illustrations' },
  Controls: { ja: 'コントロール', en: 'Controls' },
  Charts: { ja: 'グラフ', en: 'Charts' },
  Sparklines: { ja: 'スパークライン', en: 'Sparklines' },
  Filters: { ja: 'フィルター', en: 'Filters' },
  Links: { ja: 'リンク', en: 'Links' },
  Comments: { ja: 'コメント', en: 'Comments' },
  Text: { ja: 'テキスト', en: 'Text' },
  Symbols: { ja: '記号', en: 'Symbols' },
  Tools: { ja: 'ツール', en: 'Tools' },
  Pens: { ja: 'ペン', en: 'Pens' },
  Draw: { ja: '描画', en: 'Draw' },
  Themes: { ja: 'テーマ', en: 'Themes' },
  'Page Setup': { ja: 'ページ設定', en: 'Page Setup' },
  'Scale to Fit': { ja: '拡大縮小印刷', en: 'Scale to Fit' },
  'Sheet Options': { ja: 'シートのオプション', en: 'Sheet Options' },
  'Function Library': { ja: '関数ライブラリ', en: 'Function Library' },
  Python: { ja: 'Python', en: 'Python' },
  'Defined Names': { ja: '定義された名前', en: 'Defined Names' },
  'Formula Auditing': { ja: '数式の監査', en: 'Formula Auditing' },
  Calculation: { ja: '計算方法', en: 'Calculation' },
  'Sheet Views': { ja: 'シート ビュー', en: 'Sheet Views' },
  'Get & Transform Data': { ja: 'データの取得と変換', en: 'Get & Transform Data' },
  'Queries & Connections': { ja: 'クエリと接続', en: 'Queries & Connections' },
  'Data Types': { ja: 'データの種類', en: 'Data Types' },
  'Sort & Filter': { ja: '並べ替えとフィルター', en: 'Sort & Filter' },
  'Data Tools': { ja: 'データ ツール', en: 'Data Tools' },
  Forecast: { ja: '予測', en: 'Forecast' },
  Outline: { ja: 'アウトライン', en: 'Outline' },
  Analysis: { ja: '分析', en: 'Analysis' },
  Proofing: { ja: '文章校正', en: 'Proofing' },
  Accessibility: { ja: 'アクセシビリティ', en: 'Accessibility' },
  Language: { ja: '言語', en: 'Language' },
  Changes: { ja: '変更', en: 'Changes' },
  Options: { ja: 'オプション', en: 'Options' },
  Notes: { ja: 'メモ', en: 'Notes' },
  Protect: { ja: '保護', en: 'Protect' },
  'Workbook Views': { ja: 'ブックの表示', en: 'Workbook Views' },
  Show: { ja: '表示/非表示', en: 'Show' },
  Zoom: { ja: 'ズーム', en: 'Zoom' },
  Window: { ja: 'ウィンドウ', en: 'Window' },
  Macros: { ja: 'マクロ', en: 'Macros' },
  Automation: { ja: '自動化', en: 'Automation' },
  Gallery: { ja: 'ギャラリー', en: 'Gallery' },
};

export const macRibbonDisabledReason = (
  reason: string | undefined,
  lang: ToolbarLang,
): string | undefined => {
  if (!reason) return undefined;
  if (reason === OFFICE_REQUIRED.en) return OFFICE_REQUIRED[lang];
  if (reason === NOT_IMPLEMENTED.en) return NOT_IMPLEMENTED[lang];
  if (reason === EMBEDDED_UNSUPPORTED.en) return EMBEDDED_UNSUPPORTED[lang];
  if (reason === WORKBOOK_THEME_UNSUPPORTED.en) return WORKBOOK_THEME_UNSUPPORTED[lang];
  if (reason === THREADED_COMMENTS_UNSUPPORTED.en) return THREADED_COMMENTS_UNSUPPORTED[lang];
  return reason;
};

/** Localized label lookup used by both the model and the static Mac menus. */
export const macRibbonLabelForCommand = (id: string, lang: ToolbarLang): string => {
  const key = id.split('.').at(-1) ?? id;
  const label = MENU_LABELS[id] ?? labels[key];
  return label ? label[lang] : id;
};

export const MENU_LABELS: Readonly<Record<string, Label>> = {
  'mac.formulas.removeArrows.all': { ja: '矢印の削除', en: 'Remove Arrows' },
  'mac.formulas.removeArrows.precedents': {
    ja: '参照元の矢印の削除',
    en: 'Remove Precedent Arrows',
  },
  'mac.formulas.removeArrows.dependents': {
    ja: '参照先の矢印の削除',
    en: 'Remove Dependent Arrows',
  },
  'mac.formulas.errorCheck.run': { ja: 'エラー チェック...', en: 'Error Checking...' },
  'mac.formulas.errorCheck.trace': { ja: 'エラー トレース', en: 'Trace Error' },
  'mac.formulas.errorCheck.ignore': { ja: 'エラーを無視する', en: 'Ignore Error' },
  'mac.data.validation.settings': { ja: 'データの入力規則...', en: 'Data Validation...' },
  'mac.data.validation.circleInvalid': { ja: '無効データのマーク', en: 'Circle Invalid Data' },
  'mac.data.validation.clearCircles': {
    ja: '入力規則マークのクリア',
    en: 'Clear Validation Circles',
  },
  'mac.data.validation.clearRules': { ja: '入力規則のクリア', en: 'Clear Validation' },
  'mac.page.margins.normal': { ja: '標準', en: 'Normal' },
  'mac.page.margins.wide': { ja: '広い', en: 'Wide' },
  'mac.page.margins.narrow': { ja: '狭い', en: 'Narrow' },
  'mac.page.margins.custom': { ja: 'ユーザー設定の余白', en: 'Custom Margins' },
  'mac.page.orientation.portrait': { ja: '縦', en: 'Portrait' },
  'mac.page.orientation.landscape': { ja: '横', en: 'Landscape' },
  'mac.page.printArea.set': { ja: '印刷範囲の設定', en: 'Set Print Area' },
  'mac.page.printArea.add': { ja: '印刷範囲に追加', en: 'Add to Print Area' },
  'mac.page.printArea.clear': { ja: '印刷範囲のクリア', en: 'Clear Print Area' },
  'mac.formulas.createNames.topRow': { ja: '上端行', en: 'Top row' },
  'mac.formulas.createNames.bottomRow': { ja: '下端行', en: 'Bottom row' },
  'mac.formulas.createNames.leftColumn': { ja: '左端列', en: 'Left column' },
  'mac.formulas.createNames.rightColumn': { ja: '右端列', en: 'Right column' },
  'mac.data.dataTypes.stocks': { ja: '株式', en: 'Stocks' },
  'mac.data.dataTypes.geography': { ja: '地理', en: 'Geography' },
  'mac.data.goalSeek': { ja: 'ゴール シーク', en: 'Goal Seek' },
  'mac.data.scenarioManager': { ja: 'シナリオ マネージャー', en: 'Scenario Manager' },
  'mac.data.dataTable': { ja: 'データ テーブル', en: 'Data Table' },
  'mac.review.newNote': { ja: '新しいメモ', en: 'New Note' },
  'mac.review.nextNote': { ja: '次のメモ', en: 'Next Note' },
  'mac.review.previousNote': { ja: '前のメモ', en: 'Previous Note' },
  'mac.review.showNotes': { ja: 'すべてのメモを表示', en: 'Show Notes' },
  'mac.view.freeze.off': { ja: 'ウィンドウ枠固定の解除', en: 'Unfreeze Panes' },
  'mac.view.freeze.firstRow': { ja: '先頭行の固定', en: 'Freeze Top Row' },
  'mac.view.freeze.firstColumn': { ja: '先頭列の固定', en: 'Freeze First Column' },
  ...Object.fromEntries(
    MAC_AUTOMATION_GALLERY.map((script) => [
      script.commandId,
      { ja: script.labelJa, en: script.label },
    ]),
  ),
};
