import type { CellValue } from '../../../engine/types.js';
import type { State } from '../../../store/store.js';
import type { FormulaOperand } from '../types.js';

/**
 * What every per-family evaluator may draw on: the sheet being read, the rule
 * anchor that relative references resolve against, and the operand dispatcher.
 * Families re-enter `readOperand` through this object for nested operands, so
 * none of them imports `evaluator.ts`. Each family narrows it with `Pick`.
 */
export interface FormulaReaderContext {
  readonly state: State;
  readonly sheet: number;
  readonly anchorRow: number;
  readonly anchorCol: number;
  readonly readOperand: (
    operand: FormulaOperand,
    rowOffset: number,
    colOffset: number,
  ) => CellValue;
}

/** Every name `numericFunction` dispatches; each family handles a subset. */
export type NumericFunctionName =
  | 'ABS'
  | 'MOD'
  | 'ROUND'
  | 'ROUNDUP'
  | 'ROUNDDOWN'
  | 'MROUND'
  | 'QUOTIENT'
  | 'INT'
  | 'TRUNC'
  | 'SQRT'
  | 'POWER'
  | 'PI'
  | 'RADIANS'
  | 'DEGREES'
  | 'SIN'
  | 'COS'
  | 'TAN'
  | 'SEC'
  | 'CSC'
  | 'COT'
  | 'ASIN'
  | 'ACOS'
  | 'ATAN'
  | 'ATAN2'
  | 'ACOT'
  | 'SINH'
  | 'COSH'
  | 'TANH'
  | 'COTH'
  | 'SECH'
  | 'CSCH'
  | 'ASINH'
  | 'ACOSH'
  | 'ATANH'
  | 'ACOTH'
  | 'EXP'
  | 'LN'
  | 'LOG'
  | 'LOG10'
  | 'CHAR'
  | 'CODE'
  | 'UNICHAR'
  | 'UNICODE'
  | 'ADDRESS'
  | 'TYPE'
  | 'ERROR.TYPE'
  | 'FISHER'
  | 'FISHERINV'
  | 'ERF'
  | 'ERF.PRECISE'
  | 'ERFC'
  | 'ERFC.PRECISE'
  | 'GAUSS'
  | 'BASE'
  | 'DECIMAL'
  | 'BIN2DEC'
  | 'DEC2BIN'
  | 'HEX2DEC'
  | 'DEC2HEX'
  | 'OCT2DEC'
  | 'DEC2OCT'
  | 'BIN2HEX'
  | 'HEX2BIN'
  | 'BIN2OCT'
  | 'OCT2BIN'
  | 'HEX2OCT'
  | 'OCT2HEX'
  | 'ROMAN'
  | 'ARABIC'
  | 'DELTA'
  | 'GESTEP'
  | 'BITAND'
  | 'BITOR'
  | 'BITXOR'
  | 'BITLSHIFT'
  | 'BITRSHIFT'
  | 'SQRTPI'
  | 'SUMSQ'
  | 'SIGN'
  | 'GAMMA'
  | 'GAMMALN'
  | 'GAMMALN.PRECISE'
  | 'GCD'
  | 'LCM'
  | 'FACT'
  | 'FACTDOUBLE'
  | 'COMBIN'
  | 'COMBINA'
  | 'PERMUT'
  | 'PERMUTATIONA'
  | 'MULTINOMIAL'
  | 'EVEN'
  | 'ODD'
  | 'STANDARDIZE'
  | 'PHI'
  | 'CONFIDENCE'
  | 'CONFIDENCE.NORM'
  | 'CONFIDENCE.T'
  | 'PMT'
  | 'PV'
  | 'FV'
  | 'NPER'
  | 'RATE'
  | 'IPMT'
  | 'PPMT'
  | 'CUMIPMT'
  | 'CUMPRINC'
  | 'ISPMT'
  | 'EFFECT'
  | 'NOMINAL'
  | 'DOLLARDE'
  | 'DOLLARFR'
  | 'DISC'
  | 'INTRATE'
  | 'PRICEDISC'
  | 'RECEIVED'
  | 'ACCRINTM'
  | 'TBILLPRICE'
  | 'TBILLYIELD'
  | 'TBILLEQ'
  | 'RRI'
  | 'PDURATION'
  | 'SLN'
  | 'SYD'
  | 'DDB'
  | 'DB'
  | 'NORMSDIST'
  | 'NORMDIST'
  | 'NORM.S.DIST'
  | 'NORM.DIST'
  | 'NORMSINV'
  | 'NORM.S.INV'
  | 'NORMINV'
  | 'NORM.INV'
  | 'LOGINV'
  | 'LOGNORM.INV'
  | 'LOGNORMDIST'
  | 'LOGNORM.DIST'
  | 'GAMMADIST'
  | 'GAMMA.DIST'
  | 'GAMMAINV'
  | 'GAMMA.INV'
  | 'BETADIST'
  | 'BETA.DIST'
  | 'BETAINV'
  | 'BETA.INV'
  | 'FDIST'
  | 'F.DIST'
  | 'F.DIST.RT'
  | 'FINV'
  | 'F.INV'
  | 'F.INV.RT'
  | 'TDIST'
  | 'T.DIST'
  | 'T.DIST.2T'
  | 'T.DIST.RT'
  | 'TINV'
  | 'T.INV'
  | 'T.INV.2T'
  | 'CHIDIST'
  | 'CHISQ.DIST'
  | 'CHISQ.DIST.RT'
  | 'CHIINV'
  | 'CHISQ.INV'
  | 'CHISQ.INV.RT'
  | 'WEIBULL'
  | 'WEIBULL.DIST'
  | 'BINOMDIST'
  | 'BINOM.DIST'
  | 'CRITBINOM'
  | 'BINOM.INV'
  | 'NEGBINOMDIST'
  | 'NEGBINOM.DIST'
  | 'HYPGEOMDIST'
  | 'HYPGEOM.DIST'
  | 'POISSON'
  | 'POISSON.DIST'
  | 'EXPONDIST'
  | 'EXPON.DIST'
  | 'CEILING'
  | 'FLOOR'
  | 'CEILING.MATH'
  | 'FLOOR.MATH'
  | 'CEILING.PRECISE'
  | 'FLOOR.PRECISE'
  | 'ISO.CEILING';
