import type { EngineCapabilities, Workbook } from './types.js';

export const ENGINE_SPREADSHEET_PROFILE_GETTER = ['ex', 'celProfileId'].join('');
export const ENGINE_SPREADSHEET_PROFILE_SETTER = ['set', 'Ex', 'celProfileId'].join('');

/**
 * Probe the WASM module for optional bindings. As the engine grows,
 * methods are added one bundle at a time; this probe checks for each
 * method by name and flips the corresponding capability flag on iff
 * every method that flag depends on is present.
 *
 * The check is `typeof wb.<method> === 'function'`. Probing must be
 * free of side effects — the methods themselves are not invoked.
 */
export function detectCapabilities(wb: Workbook): EngineCapabilities {
  const w = wb as unknown as Record<string, unknown>;
  const has = (k: string): boolean => typeof w[k] === 'function';
  const all = (...keys: string[]): boolean => keys.every(has);

  return Object.freeze({
    merges: all('addMerge', 'getMerges', 'removeMerge', 'clearMerges'),
    cellFormatting: all(
      'getCellXfIndex',
      'setCellXfIndex',
      'getCellXf',
      'addFont',
      'addFill',
      'addBorder',
      'addNumFmt',
      'addXf',
      'getFont',
      'getFill',
      'getBorder',
      'getNumFmt',
    ),
    phonetic: all('getCellPhonetic', 'setCellPhonetic'),
    phoneticRuns: all('getCellPhoneticRuns', 'setCellPhoneticRuns'),
    defaultFont: has('setDefaultFont'),
    autoFilter: all('getSheetAutoFilterXml', 'setSheetAutoFilterXml'),
    tableMutate: all('createTable', 'updateTable', 'removeTable'),
    conditionalFormat: has('evaluateCfRange'),
    dataValidation: all('getValidations', 'addValidation', 'clearValidations'),
    sheetMutate: all('renameSheet', 'removeSheet', 'moveSheet'),
    insertDeleteRowsCols: all('insertRows', 'deleteRows', 'insertCols', 'deleteCols'),
    hiddenRowsCols: all('setRowHidden', 'setColumnHidden'),
    colRowSize: all('setColumnWidth', 'setRowHeight'),
    freeze: has('setSheetFreeze'),
    sheetView: has('getSheetView'),
    sheetZoom: has('setSheetZoom'),
    sheetTabHidden: has('setSheetTabHidden'),
    sheetVisibility: has('setSheetVisibility'),
    sheetViewFlags: all(
      'setSheetShowGridLines',
      'setSheetShowRowColHeaders',
      'setSheetShowZeros',
      'setSheetRightToLeft',
    ),
    outlines: all('setColumnOutline', 'setRowOutline'),
    comments: all('getComment', 'setComment'),
    commentsEnumerable: has('getComments'),
    hyperlinks: all('getHyperlinks', 'addHyperlink', 'clearHyperlinks'),
    definedNameMutate: has('setDefinedNameScoped'),
    definedNameScopes: all('definedNameAt', 'setDefinedNameScoped'),
    staticErrorValues: has('setError'),
    partialRecalc: has('partialRecalc'),
    iterativeProgress: has('setIterativeProgress'),
    iterativeSettings: has('getIterative'),
    spillInfo: has('spillInfo'),
    traceArrows: all('precedents', 'dependents'),
    functionMetadata: all('functionNames', 'functionMetadata'),
    functionLocale: all('localizeFunctionName', 'canonicalizeFunctionName'),
    calcMode: all('calcMode', 'setCalcMode'),
    spreadsheetProfile: all(ENGINE_SPREADSHEET_PROFILE_GETTER, ENGINE_SPREADSHEET_PROFILE_SETTER),
    sheetProtectionRoundtrip: all('getSheetProtection', 'setSheetProtection'),
    externalLinks: has('getExternalLinks'),
    lambdaText: has('getLambdaText'),
    formulaTextEvaluation: has('evaluateFormulaText'),
    arrayFormulaEvaluation: has('evaluateFormulaArray'),
    conditionalFormulaEvaluation: has('evaluateConditionalFormula'),
    cellStyles: all('cellStyleCount', 'cellStyleXfCount', 'getCellStyle', 'getCellStyleXf'),
    cellStyleMutate: all('addCellStyleXf', 'setCellStyle'),
    conditionalFormatMutate: all(
      'getConditionalFormats',
      'addConditionalFormat',
      'removeConditionalFormatAt',
      'clearConditionalFormats',
    ),
    conditionalFormatDxf: all('getDxf', 'addDxf', 'dxfCount'),
    conditionalFormatVisualMutate: has('addConditionalFormat'),
    pivotTables: all('pivotCount', 'pivotLayout'),
    pivotTableMutate: all(
      'pivotCacheCount',
      'pivotCacheIdAt',
      'pivotCacheCreate',
      'pivotCacheRemove',
      'pivotCacheFieldCount',
      'pivotCacheFieldName',
      'pivotCacheFieldAdd',
      'pivotCacheFieldClear',
      'pivotCacheRecordCount',
      'pivotCacheRecordAdd',
      'pivotCacheRecordClear',
      'pivotCreate',
      'pivotRemove',
      'pivotSetName',
      'pivotSetAnchor',
      'pivotSetGrandTotals',
      'pivotFieldCount',
      'pivotFieldAdd',
      'pivotFieldClear',
      'pivotFieldSetAxis',
      'pivotFieldSetSort',
      'pivotFieldSetSubtotalTop',
      'pivotFieldAddAggregation',
      'pivotFieldClearAggregations',
      'pivotFieldAddItem',
      'pivotFieldClearItems',
      'pivotFieldSetItemVisible',
      'pivotFieldAddSubtotalFn',
      'pivotFieldClearSubtotalFns',
      'pivotFieldSetDateGroup',
      'pivotFieldClearDateGroup',
      'pivotFieldSetNumberFormat',
      'pivotSetRowFieldOrder',
      'pivotSetColFieldOrder',
      'pivotDataFieldCount',
      'pivotDataFieldAdd',
      'pivotDataFieldClear',
      'pivotDataFieldSet',
      'pivotFilterCount',
      'pivotFilterAdd',
      'pivotFilterClear',
      'pivotFilterRemoveAt',
    ),
    pivotItemByCacheIndex: has('pivotFieldAddItemAt'),
    pivotCacheSource: all('pivotCacheGetWorksheetSource', 'pivotCacheSetWorksheetSource'),
    pivotReportLayout: all('pivotGetLayout', 'pivotSetLayout'),
    printSettings: all(
      'getSheetPageSetup',
      'setSheetPageSetup',
      'getSheetPageMargins',
      'setSheetPageMargins',
      'setSheetPrintOptions',
      'getSheetPrintOptionsXml',
      'setSheetHeaderFooter',
      'getSheetHeaderFooterXml',
      'getSheetPrintArea',
      'setSheetPrintArea',
      'getSheetPrintTitles',
      'setSheetPrintTitles',
    ),
    printSettingsXml: all('getSheetPageSetupXml', 'setSheetPageSetupXml'),
    pageBreaks: all(
      'getSheetRowBreaks',
      'getSheetColBreaks',
      'addSheetRowBreak',
      'addSheetColBreak',
      'clearSheetBreaks',
    ),
  });
}
